### ISSUE TITLE
Must turn Authentication/Authorization ON

### ISSUE THREAD

**Issue by paolorr** [adrianhall/30-days-of-zumo-v2#2]
On [day 5](https://shellmonger.com/2016/04/08/30-days-of-zumo-v2-azure-mobile-apps-day-5-custom-authentication/) you say that with custom authentication we can turn Authentication/Authorization OFF, but I got a 401 response. If I turn that on everything works perfectly. What you can turn off is Azure Active Directory Authentication, under Authentication/Authorization blade

**Comment by adrianhall** [comment]
Thanks - updated.  This was due to a change in the backend, so it's good to be caught :-)
