### ISSUE TITLE
Can't reach https://shellmonger.com

### ISSUE THREAD

**Issue by ThinhTranA** [adrianhall/30-days-of-zumo-v2#4]
Hi Adrian,
I'm been reading your book Develop Cloud Connected "Mobile Apps with Xamarin and Microsoft Azure" and learning a lot. I also found this 30-days-of-zumo post in shellmonger website. But it is down. Will you move all of its contents to https://adrianhall.github.io/ ?

**Comment by adrianhall** [comment]
The content became out of date.  The book is better, so I didn't transfer it.  I have no intent to bring it back.
